version: '3.8'

services:
  db_hotel:
    image: postgres
    restart: always
    container_name: db_hotel
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hotelDB
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
